### ISSUE TITLE
Source Request - Indonesia

### ISSUE THREAD

**Issue by heznetcom** [Paperback-iOS/extensions-beta#18]
Hello sir,
I hope you are always be healthy.

I want a request, if it's not accepted, that's okay. :)

is it possible to add web sources from Indonesia?

this is my reference:
- https://komikcast.com/
- https://kiryuu.co/
- https://westmanga.info/
- https://komikav.com/
- https://bacakomik.co/
- https://komiku.id/

note:
1. Kiryuu and Westmanga use the same theme
2. Komikcast and Komikav use similar theme

the reason why I suggest adding an Indonesian source:
- Many android users in Indonesia use the tachiyomi app, so the Paperback app can be an alternative for iOS users in Indonesia.

I have always checked the development of the paperback application every day since last November (2020), and today I created a Github account to write this request.

if there is a sentence that is not good, I am sorry, because my English is not good.

I hope dreams come true.

**Comment by ConradWeiser** [comment]
We'll add it to our list! I've copied your request over to the foreign-extensions repository at: https://github.com/Paperback-iOS/extensions-foreign/issues/4

We haven't been making any new extensions for a little while, although after the next update, we'll be clear to begin work again. I can't give a good estimation for when we'll finish with these, but having support for other languages is definitely something we're looking for!
