### ISSUE TITLE
[Bug] Genres do not show

### ISSUE THREAD

**Issue by getBoolean** [Paperback-iOS/extensions-beta#4]
(Mangakakalot, in my fork) The manga genres do not show under the description.

**Comment by ConradWeiser** [comment]
Can you list which source in specific is having this issue?

**Comment by getBoolean** [comment]
Sorry still new to github. I thought the issues were specific to the fork, didn't know they would be posted here. This was for my extension Mangakakalot

**Comment by getBoolean** [comment]
I needed to enable issues in settings. Closing this issues.
